title: Browser Tools Docs
description: Documentation for Browser Tools
theme: jekyll-theme-midnight

url: "https://renierr.github.io"
baseurl: "/browser-toolkit"

markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: ""
    values:
      layout: default
